### PR TITLE
Upgrade to Eleventy 1.0.0

### PR DESCRIPTION
**Pull request by arpitbatra123**

### CODE REVIEW

**Comment by hirusi** [comment]
This is very neat, thank you @arpitbatra123! <3

Can I ask you to take a look at the other two tasks I added to #44? Minor, but worth looking at. :)

**Comment by hirusi** [comment]
For `page.date` -- I did a project search, seems harmless as we were already converting dates to UTC in both sitemaps and for permalinks.

**Comment by hirusi** [comment]
The `slug` filter is in use on `article.liquid`:

https://github.com/hirusi/smix-eleventy-starter/blob/main/src/layouts/article.liquid#L22-L25

We should be able to update it to `slugify` no problem.

**Comment by hirusi** [comment]
Just realized there's a helper plugin and it only raises the following concerns:

```
[@11ty/eleventy-upgrade-help] PASSED `slug` to `slugify` filter
[@11ty/eleventy-upgrade-help] WARNING eleventyConfig.setDataDeepMerge(true) is the new 1.0 default. Revert with eleventyConfig.setDataDeepMerge(false);
[@11ty/eleventy-upgrade-help] WARNING The liquidjs `strictFilters` option default (in Eleventy) changed from false to true. Revert with `eleventyConfig.setLiquidOptions({ strictFilters: false })`.
[@11ty/eleventy-upgrade-help] WARNING The liquidjs `dynamicPartials` option default changed from false to true. Functionally this means `include` statements require quotes now. Revert with `eleventyConfig.setLiquidOptions({ dynamicPartials: false })`.
[@11ty/eleventy-upgrade-help] Only root .gitignore files are supported. The file at .gitignore will not be used by Eleventy. Move the entries into your project root .gitignore or use .eleventyignore instead.
```

**Comment by arpitbatra123** [comment]
Yeah, I ran this plugin and according to it, our usage of `slug` is compatible with `slugify` but since that's deprecated, I'll change it.

**Comment by hirusi** [comment]
Closes #44

**Pull request merged**
